# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      angular-security:
        applies-to: security-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      angular-eslint:
        applies-to: version-updates
        patterns:
          - "@angular-eslint/*"
          - "angular-eslint"
