packageExtensions:
  "@angular-eslint/schematics@~18.4.0":
    peerDependencies:
      "@typescript-eslint/types": "^7.11.0 || ^8.0.0"
      "@typescript-eslint/utils": "^7.11.0 || ^8.0.0"
      eslint: "^8.57.0 || ^9.0.0"
      typescript: "*"
  "@aws-amplify/ai-constructs@0.8.0":
    peerDependencies:
      "@aws-sdk/types": "^3.609.0"
      zod: ^3.22.2
  "@aws-amplify/api@~6.1.1":
    peerDependencies:
      "@aws-amplify/core": ^6.1.0
  "@aws-amplify/auth-construct@~1.4.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-auth@~1.3.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-cli@~1.4.1":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/client-sts": ^3.687.0
      aws-cdk: ^2.158.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      react: ^16.8 || ^17.0 || ^18.0
      react-dom: ^16.8 || ^17.0 || ^18.0
      typescript: ^5.0.0
  "@aws-amplify/backend-data@~1.1.7":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-deployer@~1.1.8":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/backend-function@~1.7.4":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-output-storage@~1.1.3":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      constructs: ^10.0.0
      zod: ^3.22.2
  "@aws-amplify/backend-secret@~1.1.5":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/backend-storage@~1.2.2":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend@~1.6.2":
    peerDependencies:
      "@aws-sdk/client-cloudformation": ^3.624.0
      "@aws-sdk/client-s3": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/cli-core@~1.2.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/client-config@~1.5.2":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/deployed-backend-client@~1.4.2":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/form-generator@~1.0.3":
    peerDependencies:
      react: ^16.8 || ^17.0 || ^18.0
      react-dom: ^16.8 || ^17.0 || ^18.0
  "@aws-amplify/graphql-conversation-transformer@0.6.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/graphql-default-value-transformer@~3.1.3":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/graphql-schema-generator@0.11.1":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/graphql-transformer@~2.1.6":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/model-generator@~1.0.8":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      zod: ^3.22.2
  "@aws-amplify/platform-core@~1.2.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/sandbox@~1.2.5":
    peerDependencies:
      "@aws-sdk/client-amplify": ^3.624.0
      "@aws-sdk/client-cloudformation": ^3.624.0
      "@aws-sdk/client-s3": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.686.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      typescript: ^5.0.0
  "@aws-amplify/schema-generator@~1.2.5":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/ui-angular@~5.0.30":
    peerDependencies:
      "@aws-amplify/core": "*"
  "@aws-sdk/credential-provider-ini@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.687.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
  "@aws-sdk/credential-provider-node@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.621.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.637.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.687.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.687.0
      "@aws-sdk/client-sso-oidc": ^3.686.0
  "@aws-sdk/credential-provider-sso@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.687.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
  "@aws-sdk/credential-providers@~3.687.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
  "@typescript-eslint/type-utils@~8.14.0":
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0
  "@typescript-eslint/utils@~8.14.0":
    peerDependencies:
      typescript: "*"
  angular-eslint@~18.4.0:
    peerDependencies:
      "@angular-devkit/core": ">=18.0.0 <19.0.0"
      "@angular-devkit/schematics": ">=18.0.0 <19.0.0"
      "@typescript-eslint/types": "^7.11.0 || ^8.0.0"
      "@typescript-eslint/utils": "^7.11.0 || ^8.0.0"
  typescript-eslint@~8.14.0:
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0
