packageExtensions:
  # Fixes to missing dependencies
  ## https://github.com/aws-amplify/amplify-js/issues/13024
  "@aws-amplify/auth@~6.6.0":
    dependencies:
      "@aws-crypto/sha256-js": 5.2.0
  # Fixes to broken peer dependency declarations
  "@angular-eslint/schematics@~18.4.0":
    peerDependencies:
      "@typescript-eslint/types": ^7.11.0 || ^8.0.0
      "@typescript-eslint/utils": ^7.11.0 || ^8.0.0
      eslint: ^8.57.0 || ^9.0.0
      typescript: "*"
  "@aws-amplify/ai-constructs@0.8.2":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/api@~6.1.1":
    peerDependencies:
      "@aws-amplify/core": ^6.1.0
  "@aws-amplify/auth-construct@~1.5.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-auth@~1.4.0":
    dependencies:
      # Add missing peer dependency to platform-core.
      # Visible: yarn exec amplify sandbox --once
      # Note: Listed only as dev dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fbackend-auth&name=%40aws-amplify%2Fbackend-auth&version=1.4.0&file=%2Fpackage.json
      "@aws-amplify/platform-core": ^1.0.6
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-cli@~1.4.1":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/client-sts": ^3.687.0
      aws-cdk: ^2.158.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      react: ^16.8 || ^17.0 || ^18.0
      react-dom: ^16.8 || ^17.0 || ^18.0
      typescript: ^5.0.0
      # Add missing peer dependency to tsx
      # Note: See comment for @aws-amplify/backend-deployer
      tsx: "^4.6.1"
  "@aws-amplify/backend-data@~1.2.0":
    dependencies:
      # Add missing peer dependency to platform-core.
      # Visible: yarn exec amplify sandbox --once
      # Note: Listed only as dev dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fbackend-data&name=%40aws-amplify%2Fbackend-data&version=1.2.0&file=%2Fpackage.json
      "@aws-amplify/platform-core": ^1.2.0
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-deployer@~1.1.8":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      # Add missing peer dependency to tsx
      # Visible: yarn exec amplify sandbox --once
      # Note: backend-deployer executes "yarn tsx ..." assuming tsx is
      #   top-level dependency. It is currently listed as dependency. But
      #   listing it as peer dependency through its dependency chain is needed.
      tsx: ^4.6.1
  "@aws-amplify/backend-function@~1.7.4":
    dependencies:
      # Add missing peer dependency to platform-core.
      # Visible: yarn exec amplify sandbox --once
      # Note: Listed only as dev dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fbackend-function&name=%40aws-amplify%2Fbackend-function&version=1.7.4&file=%2Fpackage.json
      "@aws-amplify/platform-core": ^1.1.0
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend-output-storage@~1.1.3":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      constructs: ^10.0.0
      zod: ^3.22.2
  "@aws-amplify/backend-secret@~1.1.5":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/backend-storage@~1.2.2":
    dependencies:
      # Add missing peer dependency to platform-core.
      # Visible: yarn exec amplify sandbox --once
      # Note: Listed only as dev dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fbackend-storage&name=%40aws-amplify%2Fbackend-storage&version=1.2.2&file=%2Fpackage.json
      "@aws-amplify/platform-core": ^1.0.6
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/backend@~1.7.0":
    peerDependencies:
      "@aws-sdk/client-cloudformation": ^3.624.0
      "@aws-sdk/client-s3": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/cli-core@~1.2.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/client-config@~1.5.2":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/deployed-backend-client@~1.4.2":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/form-generator@~1.0.3":
    peerDependencies:
      react: ^16.8 || ^17.0 || ^18.0
      react-dom: ^16.8 || ^17.0 || ^18.0
  "@aws-amplify/graphql-conversation-transformer@0.7.1":
    dependencies:
      # Add missing dependency to fs-extra
      # Visible: yarn exec amplify sandbox --once
      # Note: Not specified as any dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fgraphql-conversation-transformer&name=%40aws-amplify%2Fgraphql-conversation-transformer&version=0.7.1&file=%2Fpackage.json
      #   fs-extra version ^8.1.0 is selected based on
      #   https://github.com/search?q=repo%3Aaws-amplify%2Famplify-category-api+fs-extra+language%3AJSON&type=code
      fs-extra: ^8.1.0
      # Add missing dependency to pluralize
      # Visible: yarn exec amplify sandbox --once
      # Note: Not specified as any dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fgraphql-conversation-transformer&name=%40aws-amplify%2Fgraphql-conversation-transformer&version=0.7.1&file=%2Fpackage.json
      #   Pluralize version ^8.0.0 is selected based on
      #   https://github.com/search?q=repo%3Aaws-amplify%2Famplify-category-api+pluralize+language%3AJSON&type=code&l=JSON
      pluralize: ^8.0.0
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/graphql-default-value-transformer@~3.1.3":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/graphql-index-transformer@~3.0.8":
    dependencies:
      # Add missing dependency to pluralize
      # Visible: yarn exec amplify sandbox --once
      # Note: Not specified as any dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fgraphql-index&name=%40aws-amplify%2Fgraphql-index-transformer&version=3.0.8&file=%2Fpackage.json
      #   Pluralize version ^8.0.0 is selected based on
      #   https://github.com/search?q=repo%3Aaws-amplify%2Famplify-category-api+pluralize+language%3AJSON&type=code&l=JSON
      pluralize: ^8.0.0
  "@aws-amplify/graphql-maps-to-transformer@~4.0.8":
    dependencies:
      # Add missing dependency to graphql
      # Visible: yarn exec amplify sandbox --once
      # Note: Only listed as dev dependency
      #   https://yarnpkg.com/package?q=%40aws-amplify%2Fgraphql-maps-to-transformer&name=%40aws-amplify%2Fgraphql-maps-to-transformer&version=4.0.8&file=%2Fpackage.json
      graphql: ^15.5.0
  "@aws-amplify/graphql-schema-generator@0.11.2":
    peerDependencies:
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/graphql-transformer@~2.1.6":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      zod: ^3.22.2
  "@aws-amplify/model-generator@~1.0.8":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.686.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      zod: ^3.22.2
  "@aws-amplify/platform-core@~1.2.0":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
  "@aws-amplify/sandbox@~1.2.5":
    peerDependencies:
      "@aws-sdk/client-amplify": ^3.624.0
      "@aws-sdk/client-cloudformation": ^3.624.0
      "@aws-sdk/client-s3": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.686.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.0.0
      typescript: ^5.0.0
      # Add missing peer dependency to tsx
      # Note: See comment for @aws-amplify/backend-deployer
      tsx: ^4.6.1
  "@aws-amplify/schema-generator@~1.2.5":
    peerDependencies:
      "@aws-sdk/types": ^3.609.0
      aws-cdk-lib: ^2.158.0
      constructs: ^10.3.0
  "@aws-amplify/ui-angular@~5.0.30":
    peerDependencies:
      "@aws-amplify/core": "*"
  "@aws-sdk/credential-provider-ini@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-ini@~3.693.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.693.0
  "@aws-sdk/credential-provider-ini@~3.696.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.696.0
  "@aws-sdk/credential-provider-node@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.621.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.624.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.637.0
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-node@~3.693.0":
    peerDependencies:
      "@aws-sdk/client-sts": ^3.693.0
      "@aws-sdk/client-sso-oidc": ^3.693.0
  "@aws-sdk/credential-provider-node@~3.696.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.696.0
      "@aws-sdk/client-sts": ^3.696.0
  "@aws-sdk/credential-provider-sso@~3.621.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.624.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.637.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.614.0
  "@aws-sdk/credential-provider-sso@~3.693.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.693.0
  "@aws-sdk/credential-provider-sso@~3.696.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.696.0
  "@aws-sdk/credential-providers@~3.693.0":
    peerDependencies:
      "@aws-sdk/client-sso-oidc": ^3.693.0
  angular-eslint@~18.4.0:
    peerDependencies:
      "@angular-devkit/core": ">=18.0.0 <19.0.0"
      "@angular-devkit/schematics": ">=18.0.0 <19.0.0"
      "@typescript-eslint/types": ^7.11.0 || ^8.0.0
      "@typescript-eslint/utils": ^7.11.0 || ^8.0.0
