name: Check - Eslint

on:
  pull_request:
    paths:
      # These need to match paths in eslint.config.mjs
      - "**/*.ts"
      - "**/*.html"
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  eslint:
    name: Eslint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Create empty amplify_outputs.json to avoid errors
        run: echo '{}' > amplify_outputs.json
      - name: Lint
        run: yarn run check:eslint
