name: CI - Checks

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Format check
        run: yarn run check:prettier
      - name: Create empty amplify_outputs.json to avoid errors
        run: echo '{}' > amplify_outputs.json
      - name: Lint
        run: yarn run check:eslint

  angular-build:
    name: Angular build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Create empty amplify_outputs.json to avoid errors
        run: echo '{}' > amplify_outputs.json
      - name: Build angular
        run: yarn run ng:build

  yarn-and-dependencies:
    name: Verify yarn and dependencies are set up correctly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Check for duplicate dependencies
        run: yarn run check:yarn:dedupe
      - name: Validate peer requirements are defined
        run: |
          reqs=$(yarn explain peer-requirements)
          echo "$reqs" | grep '✘' || true
          echo "$reqs" | grep -q '✘' && exit 1 || exit 0
      - name: Validate Yarn install does not contain errors
        run: |
          errors=$(yarn install --json | jq 'select(.displayName != "YN0000")')
          error_count=$(echo "$errors" | jq -s 'length')
          if [ "$error_count" -gt 0 ]; then
            echo "Detected Yarn install errors: $error_count"
            echo "$errors"
            exit 1
          fi

  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Renovate config validation
        uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1

  validate-angular-json:
    name: Validate angular.json
    # Schema file is invalid and validating against it doesn't work
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Validate angular.json schema file exists
        run: |
          schemaFile=$(cat angular.json | jq -r '.["$schema"]')
          if [ ! -f "$schemaFile" ]; then
            echo "Schema file not found: $schemaFile"
            exit 1
          else
            echo "Schema file exists: $schemaFile"
          fi

  shellcheck:
    name: "Shellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Validate shellcheck
        run: npm run check:shellcheck
