name: Check - Format

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  format:
    name: Validate formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Format check
        run: yarn run check:prettier
