name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: corepack enable
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --immutable
      - run: yarn dedupe --check
      - name: Validate peer requirements are defined
        run: |
          reqs=$(yarn explain peer-requirements)
          echo "$reqs" | grep -q '✘' && exit 1 || exit 0
      - run: yarn run format
      - run: yarn run renovate:config
      - run: echo '{}' > amplify_outputs.json
      - run: yarn run lint
      - run: yarn run build
