name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Enable corepack to install yarn
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 22
          cache: yarn
      - name: Install yarn and project dependencies
        run: yarn install --immutable
      - name: Format check
        run: yarn run format
      - name: Create empty amplify_outputs.json to avoid errors
        run: echo '{}' > amplify_outputs.json
      - name: Lint
        run: yarn run lint
      - name: Build angular
        run: yarn run build
      - name: Renovate config validation
        run: yarn run renovate:config
      - name: Validate Yarn install does not contain errors
        run: |
          yarn install
          errors=$(yarn install --json | jq 'select(.displayName != "YN0000")' | jq -s 'length')
          if [ "$errors" -gt 0 ]; then exit 1; fi
      - name: Check for duplicate dependencies
        run: yarn dedupe --check
      - name: Validate peer requirements are defined
        run: |
          reqs=$(yarn explain peer-requirements)
          echo "$reqs" | grep '✘' || true
          echo "$reqs" | grep -q '✘' && exit 1 || exit 0
