name: ESLint

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - create-github-actions


jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
